# Generated by Django 5.1.4 on 2025-03-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_assessment_chapter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="taken_at",
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="question",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(),
        ),
    ]
