# Generated by Django 5.1.4 on 2025-03-31 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_subcategory_question_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="chosen_answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="api.question",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="time_spent",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="assessmentresult",
            name="time_taken",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
