# Generated by Django 5.1.4 on 2025-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_assessmentresult_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
