# Generated by Django 5.1.4 on 2025-04-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_created_at_assessmentresult_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="source",
            field=models.CharField(
                choices=[
                    ("student_initiated", "Student Initiated"),
                    ("teacher_generated", "Teacher Generated"),
                    ("lesson_generated", "Lesson Generated"),
                    ("exam_generated", "Exam Generated"),
                    ("admin_generated", "Admin Generated"),
                ],
                default="admin_generated",
                max_length=50,
            ),
        ),
    ]
