# Generated by Django 5.1.4 on 2025-04-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_answer_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="difficulty",
            new_name="irt_difficulty",
        ),
        migrations.AddField(
            model_name="question",
            name="ai_difficulty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="elo_difficulty",
            field=models.FloatField(default=1500),
        ),
        migrations.AlterField(
            model_name="question",
            name="guessing",
            field=models.FloatField(default=0.25),
        ),
        migrations.DeleteModel(
            name="AssessmentProgress",
        ),
    ]
