# Generated by Django 5.1.4 on 2025-04-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_userability_elo_ability_speed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userability",
            name="elo_ability",
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name="userability",
            name="elo_ability_speed",
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name="userability",
            name="irt_ability",
            field=models.FloatField(default=0),
        ),
    ]
