# Generated by Django 5.1.4 on 2025-04-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_userability_elo_ability_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userability",
            old_name="elo_ability_speed",
            new_name="elo_time_ability",
        ),
    ]
