# Generated by Django 5.1.4 on 2025-04-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_rename_elo_ability_speed_userability_elo_time_ability"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentresult",
            name="question_order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
