# Generated by Django 5.1.4 on 2025-04-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_assessmentresult_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="RLAgentState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.JSONField()),
                ("model_weights", models.BinaryField()),
            ],
        ),
    ]
