# Generated by Django 5.1.4 on 2025-04-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_rlagentstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rlagentstate",
            name="memory",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userability",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_abilities",
                to="api.user",
            ),
        ),
    ]
